# Generated by Django 6.0.3 on 2026-06-23 20:35

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postulaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('edad', models.IntegerField()),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_ventas', models.CharField(max_length=100)),
                ('disponibilidad', models.TextField()),
                ('cv_url', models.CharField(blank=True, max_length=500, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('equipamiento_audio', models.CharField(blank=True, max_length=50, null=True)),
                ('especificaciones_pc', models.CharField(blank=True, max_length=20, null=True)),
                ('conexion', models.CharField(blank=True, max_length=20, null=True)),
                ('competencias', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=30, validators=[jobs.models.validate_chilean_phone], verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('position', models.CharField(choices=[('ejecutivo_ventas', 'Ejecutivo de Ventas de Seguros'), ('ejecutivo_encuestas', 'Ejecutivo de Encuestas'), ('atencion_cliente', 'Atención al Cliente'), ('soporte_comercial', 'Soporte Comercial'), ('supervisor', 'Supervisor de Ventas')], default='ejecutivo_ventas', max_length=50, verbose_name='Puesto al que postula')),
                ('sales_experience', models.CharField(choices=[('sin_experiencia', 'No'), ('menos_1', '< 1 año'), ('1_3', '1-3 años'), ('mas_3', '+3 años')], default='sin_experiencia', max_length=20, verbose_name='Experiencia en ventas')),
                ('availability', models.TextField(blank=True, verbose_name='Disponibilidad')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Adjuntar CV (PDF o Word)')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('equipamiento_audio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipamiento de audio')),
                ('especificaciones_pc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Especificaciones de PC')),
                ('conexion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conexión')),
                ('competencias', models.CharField(blank=True, max_length=20, null=True, verbose_name='Competencias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180, verbose_name='Empresa')),
                ('contact_name', models.CharField(max_length=160, verbose_name='Nombre de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo corporativo')),
                ('phone', models.CharField(max_length=30, validators=[jobs.models.validate_chilean_phone], verbose_name='Telefono / WhatsApp')),
                ('company_size', models.CharField(choices=[('1_10', '1-10 colaboradores'), ('11_50', '11-50 colaboradores'), ('51_200', '51-200 colaboradores'), ('200_mas', '200+ colaboradores')], max_length=20, verbose_name='Tamano de empresa')),
                ('service_interest', models.CharField(choices=[('ventas_seguros', 'Venta de seguros de salud'), ('atencion_cliente', 'Atencion al cliente'), ('soporte_comercial', 'Soporte comercial'), ('outsourcing', 'Outsourcing de equipos'), ('otro', 'Otro')], max_length=40, verbose_name='Servicio de interes')),
                ('message', models.TextField(blank=True, verbose_name='Necesidad o mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
            ],
            options={
                'verbose_name': 'Contacto empresa',
                'verbose_name_plural': 'Contactos empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
