# Generated by Django 6.0.3 on 2026-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='estado',
            field=models.CharField(choices=[('Postulando', 'Postulando'), ('Califica', 'Califica'), ('No califica', 'No califica'), ('Contactado', 'Contactado'), ('Volver a llamar', 'Volver a llamar'), ('Seguna etapa', 'Seguna etapa'), ('Contratado', 'Contratado'), ('Desvinculado', 'Desvinculado'), ('Abandono', 'Abandono')], default='Postulando', max_length=40, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='application',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Observaciones'),
        ),
    ]
