# Generated by Django 6.0.3 on 2026-06-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_estado_application_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
    ]
