# Generated by Django 6.0.3 on 2026-04-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_20260331_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stitchapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
    ]
