# Generated by Django 6.0.3 on 2026-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_20260331_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_position',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('atencion_cliente', 'Atención al cliente'), ('cobranzas', 'Cobranzas')], default='vendedor', max_length=50, verbose_name='Puesto al que postula'),
        ),
    ]
