# Generated by Django 6.0.3 on 2026-04-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Adjuntar CV (PDF)'),
        ),
    ]
