# Generated by Django 6.0.3 on 2026-04-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_stitchapplication_options'),
    ]

    operations = [
    ]
