# Generated by Django 6.0.3 on 2026-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_check_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Adjuntar CV (PDF)'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(choices=[('ejecutivo_ventas', 'Ejecutivo de Ventas Seguros'), ('atencion_cliente', 'Atención al Cliente'), ('soporte_comercial', 'Soporte Comercial'), ('supervisor', 'Supervisor de Ventas')], default='ejecutivo_ventas', max_length=50, verbose_name='Puesto al que postula'),
        ),
    ]
