# Generated by Django 6.0.3 on 2026-04-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_cv_application_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stitchapplication',
            name='experience',
        ),
        migrations.AddField(
            model_name='stitchapplication',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='stitchapplication',
            name='position',
            field=models.CharField(choices=[('ejecutivo_ventas', 'Ejecutivo de Ventas Seguros'), ('atencion_cliente', 'Atención al Cliente'), ('soporte_comercial', 'Soporte Comercial'), ('supervisor', 'Supervisor de Ventas')], default='ejecutivo_ventas', max_length=50, verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='stitchapplication',
            name='sales_experience',
            field=models.CharField(choices=[('sin_experiencia', 'No'), ('menos_1', '< 1 año'), ('1_3', '1-3 años'), ('mas_3', '+3 años')], default='sin_experiencia', max_length=20, verbose_name='Experiencia en ventas'),
        ),
    ]
