# Generated by Django 6.0.3 on 2026-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_stitchapplication_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchapplication',
            name='additional_comments',
            field=models.TextField(blank=True, verbose_name='Comentarios adicionales'),
        ),
        migrations.AddField(
            model_name='stitchapplication',
            name='availability',
            field=models.TextField(blank=True, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='application',
            name='availability',
            field=models.TextField(blank=True, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sales_experience',
            field=models.CharField(choices=[('sin_experiencia', 'No'), ('menos_1', '< 1 año'), ('1_3', '1-3 años'), ('mas_3', '+3 años')], default='sin_experiencia', max_length=20, verbose_name='Experiencia en ventas'),
        ),
        migrations.AlterField(
            model_name='stitchapplication',
            name='sales_experience',
            field=models.CharField(choices=[('sin_experiencia', 'No'), ('menos_1', '< 1 año'), ('1_3', '1-3 años'), ('mas_3', '+3 años')], default='sin_experiencia', max_length=20, verbose_name='Experiencia'),
        ),
    ]
