# Generated by Django 6.0.3 on 2026-05-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_companylead_cv_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StitchApplication',
        ),
    ]
