# Generated by Django 6.0.3 on 2026-06-15 18:03

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_delete_stitchapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=30, validators=[jobs.models.validate_chilean_phone], verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='companylead',
            name='phone',
            field=models.CharField(max_length=30, validators=[jobs.models.validate_chilean_phone], verbose_name='Telefono / WhatsApp'),
        ),
    ]
