# Generated by Django 6.0.3 on 2026-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_application_phone_alter_companylead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='competencias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Competencias'),
        ),
        migrations.AddField(
            model_name='application',
            name='conexion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conexión'),
        ),
        migrations.AddField(
            model_name='application',
            name='equipamiento_audio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipamiento de audio'),
        ),
        migrations.AddField(
            model_name='application',
            name='especificaciones_pc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Especificaciones de PC'),
        ),
    ]
