# Generated by Django 6.0.3 on 2026-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_application_competencias_application_conexion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(choices=[('ejecutivo_ventas', 'Ejecutivo de Ventas de Seguros'), ('ejecutivo_encuestas', 'Ejecutivo de Encuestas')], default='ejecutivo_ventas', max_length=50, verbose_name='Puesto al que postula'),
        ),
    ]
