# Generated by Django 6.0.3 on 2026-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(choices=[('ejecutivo_ventas', 'Ejecutivo de Ventas'), ('ejecutivo_encuestas', 'Ejecutivo de Encuestas'), ('atencion_cliente', 'Atención al Cliente'), ('soporte_comercial', 'Soporte Comercial'), ('supervisor', 'Supervisor de Ventas')], default='ejecutivo_ventas', max_length=50, verbose_name='Puesto al que postula'),
        ),
    ]
